# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#prepare
# 把代码迁出
# 根据当前的package.json，创建MD5，以v2-dependencies-{{ checksum "package.json" }}作为keys，创建缓存
# 把node_modules保存在缓存，加速之后代码的运行，只要package.json不改变
#
#test
# 把代码迁出
# 把上面缓存的代码挪过来
# 把测试的结果保存到CircleCI上面
#workflows
# 让CircleCI知道脚本运行顺序
defaults: &defaults
  docker:
    - image: circleci/node:8

vewrsion: 2
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  build:
    <<: *defaults
    steps:
        - checkout
        - attach_workspace:
            at: .
        - run: yarn build
        # 持久化留给下一阶段使用
        - persist_to_workspace:
            root: .
            paths:
              - dist
              - package.json
              - LICENSE
              - README.md
  publish:
    <<: *defaults
    steps: 
        - checkout
        - attach_workspace:
            at: .
        - run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        - run: npm publish
  test:
    <<: *defaults
    steps: 
        - checkout
        - attach_workspace:
            at: .
        - run: yarn ci
        - store_test_results:
            path: test-results


workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - prepare
      - build:
          requires:
            - test
      - test:
          requires:
            - prepare
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
